# Generated by Django 2.0.1 on 2018-01-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linecount', models.IntegerField()),
                ('max_slots', models.IntegerField(default=0, help_text='0 for unlimited')),
                ('booking_deadline', models.TimeField(help_text='Booking deadline = time on the day before from which on a slot can not be reserved any more. Set this to midnight to turn off this feature completely for this station')),
                ('rnvp', models.TimeField(help_text='RVNP = Rien ne vas plus -- time when a slot can not be edited any more, set to Midnight to have the deadline as RNVP')),
                ('opened_on_weekend', models.BooleanField(default=False, help_text='Choose this option if this station will be opened on weekends')),
                ('multiple_charges', models.BooleanField(default=True, help_text='If this option is marked, the reservation form offers the opportunity to add more than one job')),
                ('has_status', models.BooleanField(default=False, help_text='This option adds a Statusbar to the job view, which shows the current loading status')),
                ('has_klv', models.BooleanField(default=False, help_text='Choose this option if you want to be able to mark charges with an KLV/NV flag')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slots.Configuration')),
            ],
            options={
                'verbose_name': 'Dock',
                'verbose_name_plural': 'Docks',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slots.Configuration')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.AddField(
            model_name='dock',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.Station'),
        ),
    ]
