# Generated by Django 2.0.1 on 2018-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='booking_deadline',
            field=models.TimeField(default='00:00:00', help_text='Booking deadline = time on the day before from which on a slot can not be reserved any more. Set this to midnight to turn off this feature completely for this station'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='linecount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='rnvp',
            field=models.TimeField(default='00:00:00', help_text='RVNP = Rien ne vas plus -- time when a slot can not be edited any more, set to Midnight to have the deadline as RNVP'),
        ),
    ]
