# Generated by Django 2.0.1 on 2018-01-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_auto_20180105_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('booking_deadline', models.TimeField(default='00:00:00', help_text='Booking deadline = time on the day before from which on a slot can not be reserved any more. Set this to midnight to turn off this feature completely for this station')),
                ('rnvp', models.TimeField(default='00:00:00', help_text='RVNP = Rien ne vas plus -- time when a slot can not be edited any more, set to Midnight to have the deadline as RNVP')),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
            },
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='booking_deadline',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='rnvp',
        ),
        migrations.RemoveField(
            model_name='dock',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='station',
            name='configuration',
        ),
        migrations.AddField(
            model_name='dock',
            name='deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='slots.Deadline'),
        ),
    ]
