# Generated by Django 2.0.1 on 2018-01-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_auto_20180108_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.AlterModelOptions(
            name='dock',
            options={'ordering': ('station', 'name'), 'verbose_name': 'Dock', 'verbose_name_plural': 'Docks'},
        ),
        migrations.AddField(
            model_name='dock',
            name='has_klv',
            field=models.BooleanField(default=False, help_text='Choose this option if you want to be able to mark charges with an KLV/NV flag'),
        ),
        migrations.AddField(
            model_name='dock',
            name='has_status',
            field=models.BooleanField(default=False, help_text='This option adds a Statusbar to the job view, which shows the current loading status'),
        ),
        migrations.AddField(
            model_name='dock',
            name='linecount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dock',
            name='max_slots',
            field=models.IntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='dock',
            name='multiple_charges',
            field=models.BooleanField(default=True, help_text='If this option is marked, the reservation form offers the opportunity to add more than one job'),
        ),
    ]
