# Generated by Django 2.0.1 on 2018-01-09 14:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0006_auto_20180108_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='dock',
            name='available_slots',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[[], [], [], [], [], [], []]),
        ),
    ]
