# Generated by Django 2.0.1 on 2018-01-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0007_dock_available_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docks', to='slots.Station'),
        ),
    ]
