# Generated by Django 2.0.1 on 2018-01-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0008_auto_20180110_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.IntegerField()),
                ('line', models.IntegerField()),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.Dock')),
            ],
            options={
                'ordering': ('dock', 'date', 'slot', 'line'),
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
            },
        ),
    ]
