# Generated by Django 2.0.1 on 2018-01-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0015_company_usercompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name': 'User Company', 'verbose_name_plural': 'User Companies'},
        ),
    ]
