# Generated by Django 2.0.1 on 2018-01-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0016_auto_20180119_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shortname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
