# Generated by Django 2.0.1 on 2018-01-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0019_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock',
            name='linecount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dock',
            name='max_slots',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'carrier'), (2, 'viewer'), (3, 'charger'), (4, 'loadmaster')], default=2),
        ),
    ]
