# Generated by Django 2.0.1 on 2018-01-19 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0020_auto_20180119_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='is_klv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
