# Generated by Django 2.0.1 on 2018-01-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0021_auto_20180119_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ('dock', 'date', 'index', 'line'), 'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='slot',
            new_name='index',
        ),
    ]
