# Generated by Django 2.0.1 on 2018-01-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0022_auto_20180122_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='dock',
            name='slotlength',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
