# Generated by Django 2.0.1 on 2018-01-23 16:09

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0023_dock_slotlength'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ('dock', django.db.models.expressions.OrderBy(django.db.models.expressions.F('date')), 'index', 'line'), 'verbose_name': 'Timelot', 'verbose_name_plural': 'Timeslots'},
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.TextField(blank=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='shortname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='booking_deadline',
            field=models.TimeField(default='00:00:00', help_text='Booking deadline = time on the day before from which on a slot can not be reserved any more. Set this to midnight to turn off this feature completely for this station', verbose_name='Booking Deadline'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='rnvp',
            field=models.TimeField(default='00:00:00', help_text='RVNP = Rien ne vas plus -- time when a slot can not be edited any more, set to Midnight to have the deadline as RNVP', verbose_name='Edit Deadline'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='available_slots',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[[], [], [], [], [], [], []], verbose_name='Available Slots'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='deadline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='slots.Deadline', verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='has_klv',
            field=models.BooleanField(default=False, help_text='Choose this option if you want to be able to mark charges with an KLV/NV flag', verbose_name='Has KLV'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='has_status',
            field=models.BooleanField(default=False, help_text='This option adds a Statusbar to the job view, which shows the current loading status', verbose_name='Has Status'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='linecount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Line Count'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='max_slots',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 for unlimited', verbose_name='Max Slots'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='multiple_charges',
            field=models.BooleanField(default=True, help_text='If this option is marked, the reservation form offers the opportunity to add more than one job', verbose_name='Multiple Charges'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='slotlength',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Slot Legth'),
        ),
        migrations.AlterField(
            model_name='dock',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docks', to='slots.Station', verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='number',
            field=models.CharField(max_length=25, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='job',
            name='payload',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 t'), (2, '2 t'), (3, '3 t'), (4, '4 t'), (5, '5 t'), (6, '6 t'), (7, '7 t'), (8, '8 t'), (9, '9 t'), (10, '10 t'), (11, '11 t'), (12, '12 t'), (13, '13 t'), (14, '14 t'), (15, '15 t'), (16, '16 t'), (17, '17 t'), (18, '18 t'), (19, '19 t'), (20, '20 t'), (21, '21 t'), (22, '22 t'), (23, '23 t'), (24, '24 t'), (25, '25 t'), (26, '26 t'), (27, '27 t'), (28, '28 t'), (29, '29 t'), (30, '30 t'), (31, '31 t'), (32, '32 t'), (33, '33 t'), (34, '34 t'), (35, '35 t'), (36, '36 t'), (37, '37 t'), (38, '38 t'), (39, '39 t'), (40, '40 t')], default=25, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='job',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.Slot', verbose_name='Slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Created'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='dock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.Dock', verbose_name='Dock'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='index',
            field=models.IntegerField(verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Is Blocked'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='is_klv',
            field=models.BooleanField(default=False, verbose_name='Is KLV'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='line',
            field=models.IntegerField(verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
