# Generated by Django 2.0.1 on 2018-01-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0025_auto_20180124_1036'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='slot',
            managers=[
            ],
        ),
    ]
