# Generated by Django 2.0.1 on 2018-01-26 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slots', '0026_auto_20180124_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCompany',
            new_name='Profile',
        ),
    ]
