# Generated by Django 2.0.1 on 2018-01-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0027_auto_20180126_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('pk',), 'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
        migrations.RemoveField(
            model_name='dock',
            name='deadline',
        ),
        migrations.AddField(
            model_name='dock',
            name='rnvp',
            field=models.PositiveSmallIntegerField(default=0, help_text='RVNP = Rien ne vas plus -- hours before the start time when a slot can not be edited any more. Set this to Zero to have the stations deadline as RNVP', verbose_name='Edit Deadline'),
        ),
        migrations.AddField(
            model_name='station',
            name='deadline',
            field=models.TimeField(default='00:00:00', help_text='Booking deadline = time on the day before from which on a slot can not be reserved any more. Set this to midnight to turn off this feature completely for this station', verbose_name='Deadline'),
        ),
        migrations.DeleteModel(
            name='Deadline',
        ),
    ]
