# Generated by Django 2.0.1 on 2018-01-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0028_auto_20180129_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='deadline',
            field=models.TimeField(default='15:00:00', help_text='Booking deadline = time on the day before from which on a slot can not be reserved any more. Set this to midnight to turn off this feature completely for this station', verbose_name='Deadline'),
        ),
    ]
